### ISSUE TITLE
Stack Empty Exception on New, when canceling save prompt.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#163]
**Describe the bug**
When choosing New from either menu bar or icon bar, and clicking cancel on the save prompt, an empty stack exception follows.

**Application**: Brain Simulator

**Module/Network**: (N/A

**To Reproduce**
1. Start Bran Simulator II with empty network.
2. Draw one synapse to dirty it.
3. Click File => New or New icon to prompt save question.
4. On save question, click Cancel.
5. Notice Empty Stack Exception as below:

**Expected behavior**
Like load and save, the stack used in suspending and resuming the engine should function correctly. 

**Screenshots**
System.InvalidOperationException: Stack empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Stack`1.Pop()
   at BrainSimulator.MainWindow.ResumeEngine() in T:\REPOSITORY\BrainSimII\BrainSimulator\MainWindowEngine.cs:line 123
   at BrainSimulator.MainWindow.button_FileNew_Click(Object sender, RoutedEventArgs e) in T:\REPOSITORY\BrainSimII\BrainSimulator\MainWindowEventHandlers.cs:line 274
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at BrainSimulator.App.Main()

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version: 2021-05-19 master

**Comment by Moorelife** [comment]
Miss-nested resume, fixed...
