### ISSUE TITLE
Occasional exception of file save

### ISSUE THREAD

**Issue by FutureAIGuru** [FutureAIGuru/BrainSimII#24]
**Describe the bug**
The exception is handled and creates a non-useful user message and is related to saving Modules in the xml file.  The exception message is at the end of this post.

This must be related to moving the xml save to a background  thread. Perhaps there is interference with the UI trying to update the display during the save.

**Application**: Brain Simulator, Neuron Engine, Neuron Server, CppEngineTest, CsEngineTest
Brain Simulatro

**Module/Network**: (if *your* network, please attach XML file)

**To Reproduce**
1. Add module to Network
2. Save the file
3. Error is occasional

**Expected behavior**
No Error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Version [v0.9a]

System.InvalidOperationException
  HResult=0x80131509
  Message=The calling thread cannot access this object because a different thread owns it.
  Source=WindowsBase
  StackTrace:
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at BrainSimulator.ModuleView.get_AreaNumber() in C:\Users\c_sim\Documents\Visual Studio 2015\Projects\BrainSimulator\BrainSimulator\ModuleViewMenu.cs:line 19
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterNeuronArray.Write59_ModuleView(String n, String ns, ModuleView o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterNeuronArray.Write60_NeuronArray(String n, String ns, NeuronArray o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterNeuronArray.Write61_NeuronArray(Object o)

  This exception was originally thrown at this call stack:
    [External Code]
    BrainSimulator.ModuleView.AreaNumber.get() in ModuleViewMenu.cs
    [External Code]

**Comment by FutureAIGuru** [comment]
If I delete the Get/Set for AreaNumber, in ModuleViewMenu.cs, the problem goes away. These are listed with 0 references and so must be secretly referenced by the xml serializer. If the problem remains fixed for several days, I'll check it in.
